# Generated by Django 5.1.1 on 2024-09-26 00:34

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'Пользователь с таким email уже существует.'}, max_length=254, unique=True, verbose_name='Email')),
                ('is_landlord', models.BooleanField(default=False, verbose_name='Является арендодателем')),
                ('is_business_account', models.BooleanField(default=False, verbose_name='Бизнес-аккаунт')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Название компании')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('additional_contact_info', models.TextField(blank=True, verbose_name='Дополнительная контактная информация')),
                ('status', models.CharField(choices=[('pending', 'Ожидание активации'), ('active', 'Активен'), ('deactivated', 'Деактивирован'), ('deleted', 'Удален')], default='pending', max_length=20, verbose_name='Статус')),
                ('status_changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения статуса')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
