# Generated by Django 5.1.1 on 2024-09-26 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property_service', '0001_initial'),
        ('review_service', '0001_initial'),
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_service.user', verbose_name='Гость'),
        ),
        migrations.AddField(
            model_name='review',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='property_service.property', verbose_name='Недвижимость'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('property', 'guest')},
        ),
    ]
