# Generated by Django 5.1.1 on 2024-09-26 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=255, verbose_name='Поисковый запрос')),
                ('filters_applied', models.JSONField(blank=True, null=True, verbose_name='Применённые фильтры')),
                ('results_count', models.IntegerField(default=0, verbose_name='Количество найденных объектов')),
                ('search_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поиска')),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('search_count', models.PositiveIntegerField(default=1)),
                ('last_searched_at', models.DateTimeField(auto_now=True, verbose_name='Последний поиск')),
            ],
        ),
        migrations.CreateModel(
            name='ViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=1, verbose_name='Количество просмотров')),
                ('last_viewed_at', models.DateTimeField(auto_now=True, verbose_name='Последний просмотр')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyViewAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_view_analytics', to='property_service.property')),
            ],
        ),
    ]
