# Generated by Django 5.1.1 on 2024-09-27 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_service', '0002_remove_property_photos_propertyimage'),
        ('search_service', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchanalytics',
            name='user',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='viewhistory',
            name='property',
        ),
        migrations.RemoveField(
            model_name='viewhistory',
            name='user',
        ),
        migrations.CreateModel(
            name='PropertyView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property_service.property', verbose_name='Недвижимость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Поисковый запрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата поиска')),
                ('results_count', models.PositiveIntegerField(default=0, verbose_name='Количество найденных результатов')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.DeleteModel(
            name='PropertyViewAnalytics',
        ),
        migrations.DeleteModel(
            name='SearchAnalytics',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
        migrations.DeleteModel(
            name='ViewHistory',
        ),
    ]
