# Generated by Django 5.1.1 on 2024-09-26 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('property_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('room', 'Комната'), ('studio', 'Студия'), ('villa', 'Вилла'), ('townhouse', 'Таунхаус'), ('bungalow', 'Бунгало'), ('hotel_room', 'Номер в отеле'), ('hostel_room', 'Номер в хостеле'), ('guesthouse', 'Гостевой дом'), ('dormitory', 'Общежитие'), ('cabin', 'Каюта'), ('cottage', 'Коттедж'), ('penthouse', 'Пентхаус'), ('loft', 'Лофт'), ('bed_and_breakfast', 'Пансионат/Отель типа "Bed and Breakfast"'), ('chalet', 'Шале'), ('farmhouse', 'Фермерский дом'), ('motel', 'Мотель')], max_length=50, verbose_name='Тип недвижимости')),
                ('rooms', models.IntegerField(default=1, verbose_name='Количество комнат')),
                ('bathrooms', models.IntegerField(default=1, verbose_name='Количество ванных комнат')),
                ('amenities', models.JSONField(blank=True, null=True, verbose_name='Удобства')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='property_photos/', verbose_name='Фотографии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
