# Generated by Django 5.1.1 on 2024-09-27 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_service', '0002_remove_property_photos_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество ванных комнат'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество комнат'),
        ),
    ]
