# Generated by Django 5.1.1 on 2024-09-27 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_service', '0003_alter_property_bathrooms_alter_property_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='property_photos/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество комнат'),
        ),
    ]
