# Generated by Django 5.1.1 on 2024-09-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая стоимость'),
        ),
    ]
