# Generated by Django 5.1.1 on 2024-09-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularPropertyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('bookings_count', models.IntegerField(default=0, verbose_name='Количество бронирований')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyViewAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=255, verbose_name='Поисковый запрос')),
                ('filters_applied', models.JSONField(blank=True, null=True, verbose_name='Применённые фильтры')),
                ('results_count', models.IntegerField(default=0, verbose_name='Количество найденных объектов')),
                ('search_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поиска')),
            ],
        ),
    ]
