# Generated by Django 5.1.1 on 2024-09-19 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics_service', '0001_initial'),
        ('property_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularpropertyanalytics',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popularity_analytics', to='property_service.property', verbose_name='Недвижимость'),
        ),
        migrations.AddField(
            model_name='propertyviewanalytics',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_analytics', to='property_service.property'),
        ),
    ]
