# Generated by Django 5.1.1 on 2024-09-19 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics_service', '0002_initial'),
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyviewanalytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_service.user'),
        ),
        migrations.AddField(
            model_name='searchanalytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.user', verbose_name='Пользователь'),
        ),
    ]
