# Generated by Django 5.1.1 on 2024-09-20 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_service', '0003_initial'),
        ('property_service', '0003_property_amenities_property_bathrooms_and_more'),
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popularpropertyanalytics',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_popularity', to='property_service.property', verbose_name='Недвижимость'),
        ),
        migrations.AlterField(
            model_name='propertyviewanalytics',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_view_analytics', to='property_service.property'),
        ),
        migrations.AlterField(
            model_name='propertyviewanalytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_property_views', to='user_service.user'),
        ),
        migrations.AlterField(
            model_name='propertyviewanalytics',
            name='view_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра'),
        ),
        migrations.AlterField(
            model_name='searchanalytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_search_history', to='user_service.user', verbose_name='Пользователь'),
        ),
    ]
